import type { LtLanguage } from "./lt.d";

// response from lt api but deduplicated
export const languages: LtLanguage[] =[
  {"name":"Arabic","code":"ar","longCode":"ar"},
	{"name":"Asturian","code":"ast","longCode":"ast-ES"},
	{"name":"Belarusian","code":"be","longCode":"be-BY"},
	{"name":"Breton","code":"br","longCode":"br-FR"},
	{"name":"Catalan","code":"ca","longCode":"ca-ES"},
	{"name":"Catalan (Valencian)","code":"ca","longCode":"ca-ES-valencia"},
	{"name":"Catalan (Balearic)","code":"ca","longCode":"ca-ES-balear"},
	{"name":"Danish","code":"da","longCode":"da-DK"},
	{"name":"German (Germany)","code":"de","longCode":"de-DE"},
	{"name":"German (Austria)","code":"de","longCode":"de-AT"},
	{"name":"German (Swiss)","code":"de","longCode":"de-CH"},
	{"name":"German (Luxembourg)","code":"de","longCode":"de-LU"},
	{"name":"Simple German","code":"de-DE-x-simple-language","longCode":"de-DE-x-simple-language"},
	{"name":"Simple German (Luxembourg)","code":"de-DE-x-simple-language","longCode":"de-DE-x-simple-language-DE"},
	{"name":"Greek","code":"el","longCode":"el-GR"},
	{"name":"English","code":"en","longCode":"en"},
	{"name":"English (US)","code":"en","longCode":"en-US"},
	{"name":"English (GB)","code":"en","longCode":"en-GB"},
	{"name":"English (Australian)","code":"en","longCode":"en-AU"},
	{"name":"English (Canadian)","code":"en","longCode":"en-CA"},
	{"name":"English (New Zealand)","code":"en","longCode":"en-NZ"},
	{"name":"English (South African)","code":"en","longCode":"en-ZA"},
	{"name":"Esperanto","code":"eo","longCode":"eo"},
	{"name":"Spanish","code":"es","longCode":"es-ES"},
	{"name":"Spanish (voseo)","code":"es","longCode":"es-AR"},
	{"name":"French","code":"fr","longCode":"fr-FR"},
	{"name":"French (Canada)","code":"fr","longCode":"fr-CA"},
	{"name":"French (Switzerland)","code":"fr","longCode":"fr-CH"},
	{"name":"French (Belgium)","code":"fr","longCode":"fr-BE"},
	{"name":"Irish","code":"ga","longCode":"ga-IE"},
	{"name":"Galician","code":"gl","longCode":"gl-ES"},
	{"name":"Japanese","code":"ja","longCode":"ja-JP"},
	{"name":"Khmer","code":"km","longCode":"km-KH"},
	{"name":"Dutch","code":"nl","longCode":"nl-NL"},
	{"name":"Dutch (Belgium)","code":"nl","longCode":"nl-BE"},
	{"name":"Polish","code":"pl","longCode":"pl-PL"},
	{"name":"Portuguese","code":"pt","longCode":"pt"},
	{"name":"Portuguese (Portugal)","code":"pt","longCode":"pt-PT"},
	{"name":"Portuguese (Brazil)","code":"pt","longCode":"pt-BR"},
	{"name":"Portuguese (Angola preAO)","code":"pt","longCode":"pt-AO"},
	{"name":"Portuguese (Moçambique preAO)","code":"pt","longCode":"pt-MZ"},
	{"name":"Romanian","code":"ro","longCode":"ro-RO"},
	{"name":"Russian","code":"ru","longCode":"ru-RU"},
	{"name":"Slovak","code":"sk","longCode":"sk-SK"},
	{"name":"Slovenian","code":"sl","longCode":"sl-SI"},
	{"name":"Tamil","code":"ta","longCode":"ta-IN"},
	{"name":"Tagalog","code":"tl","longCode":"tl-PH"},
	{"name":"Ukrainian","code":"uk","longCode":"uk-UA"},
	{"name":"Chinese","code":"zh","longCode":"zh-CN"},
	{"name":"Crimean Tatar","code":"crh","longCode":"crh-UA"},
	{"name":"Italian","code":"it","longCode":"it-IT"},
	{"name":"Persian","code":"fa","longCode":"fa-IR"},
	{"name":"Swedish","code":"sv","longCode":"sv-SE"},
]

// above list but mapped
export const languageMap = new Map(Object.entries({
  'Arabic': 'ar',
  'Asturian': 'ast-ES',
  'Belarusian': 'be-BY',
  'Breton': 'br-FR',
  'Catalan': 'ca-ES',
  'Catalan (Valencian)': 'ca-ES-valencia',
  'Catalan (Balearic)': 'ca-ES-balear',
  'Chinese': 'zh-CN',
  'Crimean Tatar': 'crh-UA',
  'Danish': 'da-DK',
  'Dutch': 'nl-NL',
  'Dutch (Belgium)': 'nl-BE',
  'English': 'en',
  'English (US)': 'en-US',
  'English (GB)': 'en-GB',
  'English (Australian)': 'en-AU',
  'English (Canadian)': 'en-CA',
  'English (New Zealand)': 'en-NZ',
  'English (South African)': 'en-ZA',
  'Esperanto': 'eo',
  'French': 'fr-FR',
  'French (Canada)': 'fr-CA',
  'French (Switzerland)': 'fr-CH',
  'French (Belgium)': 'fr-BE',
  'Galician': 'gl-ES',
  'German (Germany)': 'de-DE',
  'German (Austria)': 'de-AT',
  'German (Swiss)': 'de-CH',
  'German (Luxembourg)': 'de-LU',
  'Simple German': 'de-DE-x-simple-language',
  'Simple German (Luxembourg)': 'de-DE-x-simple-language-DE',
  'Greek': 'el-GR',
  'Irish': 'ga-IE',
  'Italian': 'it-IT',
  'Japanese': 'ja-JP',
  'Khmer': 'km-KH',
  'Persian': 'fa-IR',
  'Polish': 'pl-PL',
  'Portuguese': 'pt',
  'Portuguese (Portugal)': 'pt-PT',
  'Portuguese (Brazil)': 'pt-BR',
  'Portuguese (Angola preAO)': 'pt-AO',
  'Portuguese (Moçambique preAO)': 'pt-MZ',
  'Romanian': 'ro-RO',
  'Russian': 'ru-RU',
  'Slovak': 'sk-SK',
  'Slovenian': 'sl-SI',
  'Spanish': 'es-ES',
  'Spanish (voseo)': 'es-AR',
  'Swedish': 'sv-SE',
  'Tamil': 'ta-IN',
  'Tagalog': 'tl-PH',
  'Ukrainian': 'uk-UA',
}))
