# Generated by Django 5.1.6 on 2025-03-10 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_journalentries"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="journalentries",
            table="journal_entries",
        ),
    ]
