# Generated by Django 5.1.6 on 2025-03-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_journalentries_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentries",
            name="text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="journalentries",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
