# Generated by Django 5.1.6 on 2025-03-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_journalentries_text_alter_journalentries_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentries",
            name="decorations",
            field=models.JSONField(null=True),
        ),
    ]
