# Generated by Django 5.1.6 on 2025-04-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_journalentries_decorations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentries",
            name="decorations",
            field=models.JSONField(default=list, null=True),
        ),
    ]
