# Generated by Django 5.1.6 on 2025-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_journalentries_decorations"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentries",
            name="language",
            field=models.TextField(default="auto"),
        ),
        migrations.AddField(
            model_name="journalentries",
            name="native_language",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="journalentries",
            name="decorations",
            field=models.JSONField(default=list, null=True),
        ),
    ]
