# Generated by Django 5.1.6 on 2025-06-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_journalentries_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentries",
            name="ignore_decorations",
            field=models.JSONField(default=list, null=True),
        ),
    ]
