
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    image: kentkr/ff-backend:0.0.0
    env_file: ./backend/.env.prod

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    image: kentkr/ff-frontend:0.0.0
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    env_file:
      - ./frontend/.env

  db:
    extends:
      file: docker-compose.yml
      service: db
  
  redis:
    extends:
      file: docker-compose.yml
      service: redis

  lt:
    extends:
      file: docker-compose.yml
      service: lt
