version: "3.11"

services:
  web:
    build: .
    entrypoint: "/code/entrypoint.sh"
    command: 
      - python3 manage.py tailwind start
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  redis:
    image: redis:7
  
    #celery:
    #  build: .
    #  command: celery -A config worker -l info
    #  volumes:
    #    - .:/code
    #  env_file:
    #    - ./.env
    #  depends_on:
    #    - db
    #    - redis
    #    - web

volumes:
  postgres_data:
