
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    image: kentkr/ff-backend:0.0.0
    env_file: ./backend/.env.prod

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    image: kentkr/ff-frontend:0.0.0

  db:
    extends:
      file: docker-compose.yml
      service: db
  
  redis:
    extends:
      file: docker-compose.yml
      service: redis

  lt:
    extends:
      file: docker-compose.yml
      service: lt
