version: "3.11"

services:
  web:
    image: kentkr/ff:0.0.0
    build: .
    restart: unless-stopped
    entrypoint: "/code/entrypoint.sh"
    command: sh -c "python3 manage.py tailwind start & python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DB_HOSTNAME=db
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  postgres_data:
