
version: "3"

services:
  languagetool:
    image: erikvl87/languagetool:6.5-dockerupdate-1
    container_name: languagetool
    ports:
      - 0.0.0.0:8010:8010                        # Using default port from the image
    environment:
      - langtool_languageModel=/ngrams   # OPTIONAL: Using ngrams data
      - langtool_fasttextBinary=/fasttext
      - langtool_fasttextModel=/lid.176.bin
      - Java_Xms=512m                    # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g                      # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - /home/kylekent/languagetool/ngrams:/ngrams     # OPTIONAL: The location of ngrams data on the local machine
      # TODO: remove - fasttext is for language identification, not something we need
      - /home/kylekent/languagetool/fastText/fasttext:/fasttext
      - /home/kylekent/languagetool/fastText/lid.176.bin:/lid.176.bin
      #- /path/to/logback.xml:/LanguageTool/logback.xml:ro  # OPTIONAL: Overwrite the logging configuration
