
services:
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    image: kentkr/ff-backend:1.0.0
    env_file: ./backend/.env.prod

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    image: kentkr/ff-frontend:1.0.0
    build:
      args:
        - VITE_MODE=prod

  db:
    extends:
      file: docker-compose.yml
      service: db
    env_file: ./backend/.env.prod
  
  redis:
    extends:
      file: docker-compose.yml
      service: redis

  lt:
    extends:
      file: docker-compose.yml
      service: lt
    environment:
      - langtool_languageModel=/ngrams   # OPTIONAL: Using ngrams data
      - Java_Xms=512m                    # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g                      # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - ${HOME}/languagetool/ngrams:/ngrams     # OPTIONAL: The location of ngrams data on the local machine
volumes:
  postgres_data:
