
export const languages = [
  'English',
  'Français',
  'Español',
  'Italiano',
  'Português',
  'Deutsch',
  'Nederlands',
  'Svenska',
  'Norsk',
  'Suomi',
  'Dansk',
  'Polski',
  'Čeština',
  'Slovenčina',
  'Magyar',
  'Română',
  'Български',
  'Русский',
  'Українська',
  'ქართული',
  'العربية',
  'فارسی',
  'עברית',
  'हिन्दी',
  'বাংলা',
  'اردو',
  'தமிழ்',
  'తెలుగు',
  'ಕನ್ನಡ',
  'മലയാളം',
  'ไทย',
  'Tiếng Việt',
  '中文（简体）',
  '中文（繁體）',
  '日本語',
  '한국어',
  'Bahasa Indonesia',
  'Bahasa Melayu',
  'Filipino',
  'Esperanto',
  'Ido',
  'Interlingua',
  'Volapük',
  'Klingon (from Star Trek)',
  'Quenya (Elvish – from Tolkien)',
  'Sindarin (Elvish – from Tolkien)',
  'Dothraki (from Game of Thrones)',
  'Valyrian (from Game of Thrones)',
  'Na’vi (from Avatar)',
  'Huttese (from Star Wars)',
  'Mandalorian (Mando’a – from Star Wars)',
  'Simlish (from The Sims)',
  'Minionese (from Despicable Me)',
  'Parseltongue (from Harry Potter)',
  'Newspeak (from 1984)',
  'Láadan (feminist conlang)',
  'Leetspeak (L33tsp34k)',
  'Pirate Speak (Arrr!)',
  '🐸 Emoji Language',
  'UwU Speak',
  'Bork Bork Bork (Swedish Chef-style)',
  'LOLcat',
  'Pig Latin',
  'Gibberish',
  'Morse Code',
  'Backwards English',
  'Reversed Word Order',
  'Shakespearean English',
  'Olde English',
];
